sudo: required
language: generic
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t "$DOCKER_USERNAME"/react-production -f Dockerfile.dev .

script:
  - docker run -e CI=true "$DOCKER_USERNAME"/react-production npm run test