sudo: required
language: generic
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t "$DOCKER_USERNAME"/react-production -f Dockerfile.dev .

script:
  - docker run -e CI=true "$DOCKER_USERNAME"/react-production npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-production"
  env: "ReactProduction-env"
  bucket_name: "elasticbeanstalk-us-east-2-636982052424"
  bucket_path: "react-production"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"